export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL' 

export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET' 

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDERITEM_DETAIL_REQUEST = 'ORDERITEM_DETAILS_REQUEST'
export const ORDERITEM_DETAILS_SUCCESS = 'ORDERITEM_DETAILS_SUCCESS'
export const ORDERITEM_DETAILS_FAIL = 'ORDERITEM_DETAILLS_FAIL'

export const ORDERITEM_LIST_REQUEST = 'ORDERITEM_LIST_REQUEST'
export const ORDERITEM_LIST_SUCCESS = 'ORDERITEM_LIST_SUCCESS'
export const ORDERITEM_LIST_FAIL = 'ORDERITEM_LIST_FAIL'

export const ORDERITEM_PAY_REQUEST = 'ORDERITEM_PAY_REQUEST'
export const ORDERITEM_PAY_SUCCESS = 'ORDERITEM_PAY_SUCCESS'
export const ORDERITEM_PAY_FAIL = 'ORDERITEM_PAY_FAIL'
export const ORDERITEM_PAY_RESET = 'ORDERITEM_PAY_RESET'