# Generated by Django 4.1.1 on 2022-11-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_review_orderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
