# Generated by Django 4.1.1 on 2023-03-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order',
            new_name='order',
        ),
    ]
