# Generated by Django 4.1.1 on 2023-04-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_course_orderitem_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='paidAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
