# Generated by Django 4.1.1 on 2023-04-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_orderitem_ispaid_orderitem_paidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
