# Generated by Django 4.1.1 on 2023-04-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_course_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
