# Generated by Django 4.1.1 on 2023-04-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='upload',
            new_name='document',
        ),
    ]
