# Generated by Django 4.1.1 on 2023-04-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_upload_course_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images/'),
        ),
    ]
